# Secrets are stored as SSM Parameter Store SecureString parameters. Unlike Secrets Manager,
# ECS can't extract a JSON sub-key from a parameter at injection time, so the DB password and the
# full connection string are kept as separate parameters rather than one JSON blob.
#
# Values are generated by Terraform (random_password) rather than set out-of-band: a manual
# post-apply step here is easy to forget (it was — see incident where every deploy's DB
# migration crashed for months because the placeholder value was never replaced) and Terraform
# state already carries equivalent sensitivity to these SSM parameters for this project (S3
# backend, access-controlled, versioned). random_password is stable across applies unless
# explicitly tainted, so this does not rotate secrets on every `terraform apply`.

resource "random_password" "db_password" {
  length  = 32
  special = false # RDS master password forbids '/', '@', '"', and space; keep it simple.
}

resource "random_password" "jwt_key" {
  length = 48
}

resource "random_password" "seed_hmac_key" {
  length = 48
}

# DB master password — sourced by RDS as the master password (see rds.tf).
resource "aws_ssm_parameter" "db_password" {
  name  = "/${local.prefix}/db/password"
  type  = "SecureString"
  value = random_password.db_password.result
}

# Full DB connection string injected into ECS tasks as ConnectionStrings__DefaultConnection.
resource "aws_ssm_parameter" "db_connection_string" {
  name  = "/${local.prefix}/db/connection-string"
  type  = "SecureString"
  value = "Host=${aws_db_instance.main.address};Port=5432;Database=${var.db_name};Username=${var.db_username};Password=${random_password.db_password.result}"
}

# JWT signing key.
resource "aws_ssm_parameter" "jwt_key" {
  name  = "/${local.prefix}/jwt-key"
  type  = "SecureString"
  value = random_password.jwt_key.result
}

# Seed-admin HMAC key — the secret that makes the seeded admin's daily password unguessable.
# Injected into the API task as Seed__HmacKey.
resource "aws_ssm_parameter" "seed_hmac_key" {
  name  = "/${local.prefix}/seed-hmac-key"
  type  = "SecureString"
  value = random_password.seed_hmac_key.result
}
